spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${CLIENT_ID}
            client-secret: ${CLIENT_SECRET}
exambyte:
  rollen:
    organisator: 114222016, 61031171
    korrektor:
    student: 114227946