@startuml
'https://plantuml.com/class-diagram
[Domain Model] <<..domain.model..>>
[Domain Service] <<..domain.service..>>
[Application Service] <<..application.service..>>
[webAdapter] <<..controllers..>>
[persistenceAdapter] <<..repositories..>>
[configAdapter] <<..configuration..>>

[webAdapter] --> [Application Service]
[webAdapter] --> [Domain Model]
[webAdapter] --> [Domain Service]
[persistenceAdapter] --> [Domain Service]
[persistenceAdapter] --> [Domain Model]
[configAdapter] --> [Application Service]
[configAdapter] --> [Domain Service]
[configAdapter] --> [Domain Model]
[Domain Service] --> [Domain Model]
[Application Service] --> [Domain Service]
[Application Service] --> [Domain Model]

@enduml